language: php

php:
- 7.1
- 7.0
- 5.6
- 5.5
- 5.4
- 5.3
- 5.2

sudo: false

before_script:
- echo 'extension="redis.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script: phpunit --verbose --testdox