language: php

php:
- 7.1
- 7.0
- 5.6

sudo: required 

before_script:
- echo "bind 127.0.0.1" > /tmp/redis.conf
- echo "port 6379" >> /tmp/redis.conf
- echo "unixsocket /tmp/redis.sock" >> /tmp/redis.conf
- echo "unixsocketperm 777" >> /tmp/redis.conf
- echo "requirepass foobared" >> /tmp/redis.conf
- echo "daemonize yes" >> /tmp/redis.conf
- sudo redis-server /tmp/redis.conf

script:
- phpunit --coverage-clover=coverage.xml --testdox

after_success:
- bash <(curl -s https://codecov.io/bash)
